<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Code analysis -->
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />

    <!-- Testing (Rtg.Tests) -->
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />

    <!-- Web / API (Rtg.Api) -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />

    <!-- Hosting (Rtg.Listener) -->
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
  </ItemGroup>
</Project>
